---
- hosts: webServer
  become: yes
  tasks:
  - name: installing apache
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: install php packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - php
    - libapache2-mod-php
    - php-mcrypt
    - php-mysql
    - php-cli  
  - name: restart service
    service:
      name: apache2
      state: restarted
      enabled: yes
  - name: copy php file
    copy:
      src: info.php
      dest: /var/www/html/info.php    
