---
- hosts: all
  become: yes
  vars:
    tomcatopt:
      - tomcat7-docs 
      - tomcat7-admin
      - tomcat7-examples
      - default-jdk
      - ant 
      - git
  tasks:
  - name: update and installing tomcat
    apt:
      name: tomcat7
      state: present
      update_cache: yes   
  - name: java parameters
    copy:
      src: tomcat
      dest:  /etc/default/tomcat7
    notify:
    - Restart Tomcat7
  - name: installing tomcat packages
    apt:
      name: "{{ tomcatopt }}"
      state: present
    notify:
    - Restart Tomcat7  
  - name: tomcat web management
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat7/tomcat-users.xml
  - name: Deploy WAR File
    copy:
      src: /home/ubuntu/terraform/openmrs.war
      dest: /var/lib/tomcat7/webapps/openmrs.war
    notify:
    - Restart Tomcat7 
  handlers:
  - name: Restart Tomcat7
    service:
      name: tomcat7
      enabled: yes
      state: restarted