---
- hosts: NODE
  become: yes
  tasks:
  - name: update and installing tomcat
    apt:
      name: tomcat7
      state: present
      update_cache: yes   
  - name: java parameters
    copy:
      src: tomcat7
      dest:  /etc/default/tomcat7
    notify:
    - Restart Tomcat7
  - name: installing tomcat packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - tomcat7-docs 
    - tomcat7-admin
    - tomcat7-examples
    - default-jdk
    - ant 
    - git 
    notify:
    - Restart Tomcat7  
  - name: tomcat web management
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat7/tomcat-users.xml
  - name: Deploy WAR File
    copy:
      src: /home/ansible/workspace/gameoflife/gameoflife-web/target/gameoflife.war
      dest: /var/lib/tomcat7/webapps/gameoflife.war
    notify:
    - Restart Tomcat7 
  handlers:
  - name: Restart Tomcat7
    service:
      name: tomcat7
      enabled: yes
      state: restarted   